### ISSUE TITLE
Create Models

### ISSUE THREAD

**Issue by cabralwilliams** [cabralwilliams/the-missing-one#1]
## Case Model

**Comment by Ivonnor1975** [comment]
Case 
-array of user IDs (people collaborating on case)
-status case (open, or closed)
- notes from searchers (people collaborating on case)

**Comment by Ivonnor1975** [comment]
location
Case
-array of user IDs (people collaborating on case)
-status case (open, or closed)

notes from searchers (people collaborating on case)
-place last time seen
